import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Header } from '_components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'NextJS playground',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<div className="min-h-screen p-8 bg-slate-800">
					<main className="mx-auto flex-col items-center justify-between w-full max-w-4xl">{children}</main>
				</div>
			</body>
		</html>
	);
}
